apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-deployment
  labels:
    app: greetings
    type: backend
spec:
  template:
    metadata:
      name: greetings-pod
      labels:
        app: greetings
        type: backend
    spec:
      containers:
        - name: greetings-backend-container
          image: greetings-backend:latest
          ports:
            - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: greetings
      type: backend
---
apiVersion: v1
kind: Service
metadata:
  name: greetings-service
  labels:
    app: greetings
    type: backend

